import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Structure comes from each page's sidebar_position and each folder's
// _category_.json, both generated by tools/migrate.py.
const sidebars: SidebarsConfig = {
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
