/**
 * Legacy hash redirects.
 *
 * The Slate site was a single page: every deep link into the docs looks like
 * https://doc.navitia.io/#journeys. A URL fragment is never sent to the
 * server, so no HTTP-level redirect can catch these -- the mapping has to be
 * applied client-side, once, on the landing page.
 *
 * The map is generated by tools/migrate.py from the same anchor index used to
 * rewrite the in-page links, so the two can never drift apart.
 */
import siteConfig from '@generated/docusaurus.config';
import redirects from '@site/static/legacy-redirects.json';

const MAP = redirects as Record<string, string>;

// The site root is baseUrl, not necessarily "/": on GitHub Pages the docs are
// served from a subpath. Targets in the map are baseUrl-relative too.
const BASE = siteConfig.baseUrl;

export function onRouteDidUpdate({location}: {location: Location}): void {
  if (typeof window === 'undefined') {
    return;
  }
  // Old links only ever pointed at the site root.
  if (location.pathname !== BASE && location.pathname !== `${BASE}index.html`) {
    return;
  }
  const hash = decodeURIComponent(location.hash.replace(/^#/, ''));
  if (!hash) {
    return;
  }
  const target = MAP[hash];
  // Anchors that still live on the landing page need no redirect.
  if (!target || target.startsWith('/#')) {
    return;
  }
  window.location.replace(BASE.replace(/\/$/, '') + target);
}
